# nixpacks.toml

[phases.setup]
providers = ['go', 'swag']
nixPkgs = ['go']

[phases.build]
cmds = [
    'echo Hello!',
    'echo folder content:; ls;',
    'cd mpbs-protobuf; ./generate-be.sh',
    'cd mpbs-be; wag init main.go --output docs;',
    'cd mpbs-be; go build -o out;'
]

[start]
cmd = './out'