# nixpacks.toml

[phases.setup]
providers = ['go', 'swag', 'brew']
nixPkgs = ['go']
cmds = ['brew install protobuf']
paths = ['/opt/homebrew/opt/protobuf@3/bin']

[phases.build]
cmds = [
    'echo Starting Go backend build.',
    'echo Generating Go protos; cd mpbs-protobuf; ./generate-be.sh',
    'echo Generating Swagger documentation; cd mpbs-be; swag init main.go --output docs;',
    'echo Buildin Go project; cd mpbs-be; go build -o out;'
]

[start]
cmd = 'cd mpbs-be; ./out;'