# nixpacks.toml

[phases.setup]
providers = ['go', 'swag']
nixPkgs = ['go']

[phases.build]
cmds = [
    'echo Hello!',
    'cd ..; echo folder content:; ls;',
    '../mpbs-be/generate-be.sh',
    'echo Hello 4!',
    'swag init main.go --output docs',
    'go build -o out'
]

[start]
cmd = './out'