FROM node:16.15.1-alpine as node

WORKDIR /app

RUN apk update && apk upgrade && apk add bash && apk add protobuf

RUN mkdir -p mpbs-fe
RUN mkdir -p mpbs-protobuf

COPY ../mpbs-fe ./mpbs-fe
COPY ../mpbs-protobuf/api ./mpbs-protobuf/api
COPY ../mpbs-protobuf/package.json ./mpbs-protobuf/package.json
COPY ../mpbs-protobuf/generate-fe.sh ./mpbs-protobuf/generate-fe.sh

WORKDIR /app/mpbs-protobuf
RUN npm install
RUN ./generate-fe.sh

WORKDIR /app/mpbs-fe
RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY --from=node /app/mpbs-fe/dist/mpbs-fe /usr/share/nginx/html
COPY --from=node /app/mpbs-fe/nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 7921
