# nixpacks.toml

[phases.setup]
providers = ['...', 'swag', 'sh']
nixPkgs = ['...']

[phases.build]
cmds = [
    'echo Hello!',
    'sh ../mpbs-protobuf/generate-be.sh',
    'swag init main.go --output docs',
    'go build -o out'
]

[start]
cmd = './out'