# nixpacks.toml

[phases.setup]
providers = ['...', 'swag']
nixPkgs = ['...']

[phases.build]
cmds = [
    'sh ../mpbs-protobuf/generate-be.sh',
    'swag init main.go --output docs',
    'go build -o out'
]

[start]
cmd = './out'