name: MPBS-FE deployment to github pages
run-name: ${{ github.actor }} deploying to github pages
on:
  push:
    branches:
      - master
jobs:
  ng-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: ng deploy --base-href=https://GithubUserName.github.io/GithubRepoName/
